#!/bin/sh
SIZE="data-height=\"240px\" data-width=\"427px\"" #FIXME
if [ -n "$2" ]; then
	DLANG=" data-language=\"$1\""
	shift
fi

cat <<EOF
<!DOCTYPE html>
<html>
<head>
<title>$1</title>
<meta charset="UTF-8">
<script src='https://amara.org/embedder-iframe'></script>
<style>
div.amara-embed {
	display: inline-block;
	margin: 5px;
}
</style>
</head>
<body>
<h1>$1</h1>
EOF
sed "s#.*#<div class=\"amara-embed\" $SIZE data-url=\"&\"$DLANG></div>#" -
cat <<EOF
</body>
</html>
EOF
